### ISSUE TITLE
Installation issue: Sanger::CGP::Tophat::Implement doesn't compile

### ISSUE THREAD

**Issue by AndyMenzies** [cancerit/cgpRna#19]
As of hotfix 2.1.8 Sanger::CGP::Tophat::Implement doesn't compile.

reports the following error

Failed test 'use Sanger::CGP::Tophat::Implement;' at t/1_pm_compile.t line 35.
Tried to use 'Sanger::CGP::Tophat::Implement'.
Error:  Global symbol "$output_post" requires explicit package name at /nfs/users/nfs_c/cgppipe/git/canPipe/install_tmp/cgpRna/perl/blib/lib/Sanger/CGP/Tophat/Implement.pm line 539.
Global symbol "$output_post" requires explicit package name at /nfs/users/nfs_c/cgppipe/git/canPipe/install_tmp/cgpRna/perl/blib/lib/Sanger/CGP/Tophat/Implement.pm line 540.
Global symbol "$output_post" requires explicit package name at /nfs/users/nfs_c/cgppipe/git/canPipe/install_tmp/cgpRna/perl/blib/lib/Sanger/CGP/Tophat/Implement.pm line 541.
Compilation failed in require at t/1_pm_compile.t line 35.
BEGIN failed--compilation aborted at t/1_pm_compile.t line 35.

**Comment by keiranmraine** [comment]
@AndyMenzies did you talk to @drjsanger ?

**Comment by drjsanger** [comment]
Fixed by c561f81
